from datetime import datetime
from typing import Protocol

from app.domain.entities.queue_entry import QueueEntry


class QueueRepository(Protocol):
    def add(self, entry: QueueEntry) -> QueueEntry: ...
    def get(self, entry_id: int) -> QueueEntry | None: ...
    def list_waiting(self, restaurant_id: int) -> list[QueueEntry]: ...
    def list_active(self, restaurant_id: int) -> list[QueueEntry]: ...
    def position(self, entry: QueueEntry) -> int | None: ...
    def call_next(self, restaurant_id: int, called_at: datetime) -> QueueEntry | None: ...
    def transition(self, entry_id: int, expected, new_status, at: datetime) -> QueueEntry | None: ...
    def entries_between(self, restaurant_id: int, start: datetime, end: datetime) -> list[QueueEntry]: ...
